[package]
name = "cacao"
description = "Rust bindings for AppKit (macOS) and UIKit (iOS/tvOS). Experimental, but working!"
version = "0.1.0"
edition = "2018"
authors = ["Ryan McGrath <ryan@rymc.io>"]
build = "build.rs"
repository = "https://github.com/ryanmcgrath/cacao"
categories = ["gui", "os::macos-apis", "os::ios-apis"]
keywords = ["gui", "macos", "ios", "appkit", "uikit"]

[dependencies]
block = "0.1.6"
core-foundation = { version = "0.7", features = ["with-chrono"] }
core-graphics = "0.19.0"
dispatch = "0.2.0"
libc = "0.2"
objc = "0.2.7"
objc_id = "0.1.1"
uuid = { version = "0.8", features = ["v4"], optional = true }
url = "2.1.1"

[features]
default = ["macos"]
macos = []
cloudkit = []
user-notifications = ["uuid"]
webview = []
webview-downloading = []
