[package]
name = "cacao"
description = "Rust bindings for AppKit (macOS) and UIKit (iOS/tvOS). Experimental, but working!"
version = "0.1.0"
edition = "2018"
authors = ["Ryan McGrath <ryan@rymc.io>"]
build = "build.rs"
repository = "https://github.com/ryanmcgrath/cacao"
categories = ["gui", "os::macos-apis", "os::ios-apis"]
keywords = ["gui", "macos", "ios", "appkit", "uikit"]

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"

[dependencies]
block = "0.1.6"
core-foundation = { version = "0.9", features = ["with-chrono", "mac_os_10_8_features"] }
core-graphics = "0.22"
dispatch = "0.2.0"
lazy_static = "1.4.0"
libc = "0.2"
objc = "0.2.7"
objc_id = "0.1.1"
os_info = "3.0.1"
uuid = { version = "0.8", features = ["v4"], optional = true }
url = "2.1.1"

[dev-dependencies]
eval = "0.4"

[features]
default = ["macos"]
cloudkit = []
ios = []
macos = []
color_fallbacks = []
quicklook = []
user-notifications = ["uuid"]
webview = []
webview-downloading = []
